# Generated by Django 4.2.4 on 2023-09-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='description',
            field=models.TextField(default='Lorem'),
        ),
        migrations.AddField(
            model_name='events',
            name='venue',
            field=models.CharField(default='Lagos', max_length=100),
        ),
    ]
